### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by omares** [xunit/xamarinstudio.xunit#6] opened 2015-05-22 12:33 UTC
The documentation for the plugin is very sparse and a simple installation does not run any xunit tests at all for us.

Could you please answer following questions:
- Which nuget packages should be installed?
- What steps are required to get the plugin to run?

Thank you

**Comment by x2bool** [comment] 2015-05-22 19:23
Hi! Sorry for the lack of documentation. I hope it will be released soon.

You have to reference xunit dlls to get the plugin working (so far only versions 1.x are supported).
The http://www.nuget.org/packages/xunit/1.9.2 package works for me.

Make sure you reference 1.x dlls. This is the most common reason why people can't get the plugin to work with their projects.

**Comment by omares** [comment] 2015-06-20 00:07
Hey @x2bool, any news on the 2.0.0 support?

**Comment by x2bool** [comment] 2015-06-23 09:37
@omares Not yet. The last time I checked the 2.0 runner didn't work on Mono.

**Comment by tomitrescak** [comment] 2015-07-13 14:16
Still no luck for me:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="xunit" version="1.9.2" targetFramework="net45" />
</packages>
```

Test runner is not picking up the tests :/

**Comment by eatdrinksleepcode** [comment] 2015-07-25 03:00
I also have version 1.9.2 of xunit and the test runner will not find the tests. Any ideas?

**Comment by molinch** [comment] 2015-09-02 15:35
Thanks for the great job!
Hi @x2bool do you have any plan to integrate xUnit2?

**Comment by x2bool** [comment] 2015-09-04 13:56
Hi, everyone. I finally have some time to work on the project. Let's see what I can do.

**Comment by x2bool** [comment] 2015-09-05 08:38
@molinch Seems like I can't do anything until mono 4.2.0 is released. The runner doesn't work properly on 4.0.3. You can find more info here: https://github.com/xunit/xunit/issues/158

**Comment by valdetero** [comment] 2015-10-28 22:16
Since mono 4.2 and xUnit 2.1 are released, is this issue resolved?

**Comment by x2bool** [comment] 2015-11-03 16:41
@valdetero No, it won't be resolved by itself. Some amount of work is required to run 2.0 tests. Can't promise anything, but at least I can look whether the runner still crashes on mono.

**Comment by lextm** [comment] 2016-01-24 07:17
Tried to use xUnit.net 2.2.0 beta 1 on Mono 4.3.3 and OS X El Capitan, and it seems to work without exceptions.

I think it is better to have xUnit.net 2.\* support enabled by default, and allow users to disable that if it fails to work. Right now we just have no option to choose but to wait.

**Comment by x2bool** [comment] 2016-01-24 19:29
@lextm Seems like xunit/xunit#158 is still open. The last time I checked it had the same problems as before. This stuff with AppDomains is really tricky.

**Comment by dmunch** [comment] 2016-01-30 09:28
@x2bool The issue is closed now, and I can confirm I'm able to run unit tests on Mono 4.2 wit the xunit console runner. Is there any more work expected to make the Xamarin Studio Plugin work with xUnit 2.\* ? I'd really love to see it working soon, and if there's anything we can do for giving a helping hand let us know!

**Comment by x2bool** [comment] 2016-02-06 09:17
Hi everyone! Short update: the framework seems to work well with the latest Mono version, but there is another problem: the original Xamarin Studio's runner is really hard to extend and tightly coupled with NUnit. I've already been doing some hacky stuff to support xunit 1.0. The 2.0 version brings additional complexity and it will be a nightmare to support all that.

The good news is that I am in the middle of a "proof of a concept" project which is basically a fork of Xamarin Studio's test runner, and everything seems okay so far. It is very unlikely that I will be capable to integrate changes to back to https://github.com/mono/monodevelop, but I think it will be worth the effort because of the new ASP.NET 5 / .NET Core stuff coming to Xamarin Studio. So expect it to be released as a standalone plugin.

Let's see what I can do.

**Comment by jacqueline-homan** [comment] 2016-02-06 10:36
OK. Just want to chime in here. I have Xamarin Studio on my Mac and Monodevelop on my Debian-Linux. The Monodevelop does not behave the same as the Xamarin does. When you mouse over code, you don't get that Intellisense window that pops up and tells you about the type signature or anything like you do with Xamarin. And also, there are hardly any features at all available to me on the Monodevelop for Linux. I should think that if Monodevelop and Xamarin are the same thing, then they would have the same things. Since I am presently away from my Mac and on my Linux desktop, here is a screenshot from the Linux of Monodevelop:
![monodevelop](https://cloud.githubusercontent.com/assets/3537889/12866193/7e8d5dd6-cc93-11e5-9690-76d4269fab86.jpg)

**Comment by jacqueline-homan** [comment] 2016-02-06 11:21
At least I can do most F# stuff (if I couldn't do any F# stuff in Mono I'd be really cranky),except WebSharper. Since Monodevelop's update, I think that the issue of running WebSharper in it might be fixed. I haven't tried using it yet, so I don't know.

**Comment by x2bool** [comment] 2016-02-06 12:28
@jacqueline-homan How is this related to xUnit test runner?

**Comment by jacqueline-homan** [comment] 2016-02-06 13:02
xUnit may be one of the things that don't always work reliably in
Monodevelop. That's all I was trying to say.

On Sat, Feb 6, 2016 at 7:28 AM, Sergey Khabibullin <notifications@github.com

> wrote:
> 
> @jacqueline-homan https://github.com/jacqueline-homan How is this
> related to xUnit test runner?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/xunit/xamarinstudio.xunit/issues/6#issuecomment-180752424
> .

## 

[image: --]
Jacqueline Homan
[image: http://]about.me/jacqueline_homan
http://about.me/jacqueline_homan

**Comment by lextm** [comment] 2016-02-06 15:18
@x2bool I was trying to build and debug this addin today and finally got it compiled and launched in MonoDevelop on Linux. Neither Xamarin nor you put a "how to contribute" doc somewhere so that wasting my time on both OS X and Windows before trying Linux.

Yes, it is weird to me that this addin depends on the NUnit addin. If you do plan to rewrite it from scratch, do you already have the code somewhere so that I can play with? It would be an interesting project overall.

**Comment by lextm** [comment] 2016-05-02 08:07
Closed #10, as I published a separate addin http://addins.monodevelop.com/Project/Index/220

MonoDevelop/Xamarin Studio has changed a lot in 6.0, which makes it almost a rewrite to support that new IDE. I will try to work under https://github.com/lextm/xamarinstudio.xunit/tree/6.0

And if anyone wants to join the hack, let me know.

**Comment by lextm** [comment] 2016-05-23 02:40
Just an update here that my fork now supports both 
- MonoDevelop/Xamarin Studio 5.x
- MonoDevelop/Xamarin Studio 6

Should still be considered as beta quality, as many basic functionality is still missing, but the progress looks good.

**Comment by x2bool** [comment] 2016-05-23 09:48
Hi @lextm! Would you like to take over this repo? I don't really have time to work on this, and I don't work with Xamarin Studio at the moment. Your progress seems great.

**Comment by lextm** [comment] 2016-05-23 13:47
@x2bool I am OK to take ownership of this repo and drive it further. Let me know what I should do on my side to take it over.

**Comment by x2bool** [comment] 2016-05-23 15:00
@bradwilson Can you please give the access to @lextm? His fork is probably a step forward since a lot of things have changed in Xamarin Studio in version 6.0, and I think it's better to keep the updated version of this plugin here. What do you think?

**Comment by bradwilson** [comment] 2016-05-23 17:39
@x2bool @lextm Okay, I've removed the old team, and added both of you as individual administrators for this project.

**Comment by lextm** [comment] 2016-05-30 08:45
Temp close this long thread.

The documentation on how to install the add-in has been added to Readme.md. Running it is quite similar to how to run the NUnit add-in.

New issues should be opened if anything requires further attention. Thanks.

**Closed as completed by lextm** 2016-05-30 08:45 UTC
Labels: question
