### ISSUE TITLE
Error loading template id XUnitProject in addin MonoDevelop.XUnit.XUnit

### ISSUE THREAD

**Issue by sushihangover** [xunit/xamarinstudio.xunit#8] opened 2015-07-02 19:47 UTC
Installing version 0.5 via the add-in manager in XS  5.9.4, I receive the following in the IDE log when starting XS:

```
ERROR [2015-07-02 12:36:30Z]: Error loading template id XUnitProject in addin MonoDevelop.XUnit.XUnit:
System.ApplicationException: Template XUnitProject.xpt.xml not found
  at MonoDevelop.Ide.Codons.ProjectTemplateCodon.GetTemplate () [0x0009c] in /Users/builder/data/lanes/1881/8010a90f/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Codons/ProjectTemplateCodon.cs:66 
  at MonoDevelop.Ide.Templates.ProjectTemplate..ctor (Mono.Addins.RuntimeAddin addin, System.String id, MonoDevelop.Ide.Codons.ProjectTemplateCodon codon, System.String overrideLanguage) [0x0002c] in /Users/builder/data/lanes/1881/8010a90f/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs:193 
  at MonoDevelop.Ide.Templates.ProjectTemplate.OnExtensionChanged (System.Object s, Mono.Addins.ExtensionNodeEventArgs args) [0x0002d] in /Users/builder/data/lanes/1881/8010a90f/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs:412 
```
#### Install info:

Xamarin Studio
Version 5.9.4 (build 5)
Runtime:
    Mono 4.0.2 ((detached/c99aa0c)
    GTK+ 2.24.23 (Raleigh theme)
    Package version: 400020005

**Comment by tomitrescak** [comment] 2015-07-13 11:38
:+1: same here

**Comment by tomitrescak** [comment] 2015-07-13 11:44
Downgraded to 5.8.4. Same Error

```
ERROR [2015-07-13 21:42:28Z]: Error loading template id XUnitTestClass in addin MonoDevelop.XUnit.XUnit:
System.ApplicationException: Template XUnitTestClass.xft.xml not found
  at MonoDevelop.Ide.Codons.ProjectTemplateCodon.GetTemplate () [0x0009c] in /Users/builder/data/lanes/1550/6e8e725e/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Codons/ProjectTemplateCodon.cs:66 
  at MonoDevelop.Ide.Templates.FileTemplate.LoadFileTemplate (Mono.Addins.RuntimeAddin addin, MonoDevelop.Ide.Codons.ProjectTemplateCodon codon) [0x00002] in /Users/builder/data/lanes/1550/6e8e725e/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs:148 
  at MonoDevelop.Ide.Templates.FileTemplate.OnExtensionChanged (System.Object s, Mono.Addins.ExtensionNodeEventArgs args) [0x00021] in /Users/builder/data/lanes/1550/6e8e725e/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs:252 
ERROR [2015-07-13 21:42:28Z]: Error loading template id XUnitProject in addin MonoDevelop.XUnit.XUnit:
System.ApplicationException: Template XUnitProject.xpt.xml not found
  at MonoDevelop.Ide.Codons.ProjectTemplateCodon.GetTemplate () [0x0009c] in /Users/builder/data/lanes/1550/6e8e725e/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Codons/ProjectTemplateCodon.cs:66 
  at MonoDevelop.Ide.Templates.ProjectTemplate..ctor (Mono.Addins.RuntimeAddin addin, System.String id, MonoDevelop.Ide.Codons.ProjectTemplateCodon codon, System.String overrideLanguage) [0x0002c] in /Users/builder/data/lanes/1550/6e8e725e/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs:138 
  at MonoDevelop.Ide.Templates.ProjectTemplate.OnExtensionChanged (System.Object s, Mono.Addins.ExtensionNodeEventArgs args) [0x0002d] in /Users/builder/data/lanes/1550/6e8e725e/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs:288 
```

**Comment by lextm** [comment] 2016-05-28 07:35
Can anyone try to install 0.5.2 following Readme.md on Xamarin Studio 5.10? I think it has been resolved already.

**Comment by lextm** [comment] 2016-05-30 08:42
Temp close this one, as I could not reproduce it with latest IDE and this add-in.

Can re-open it if anyone meets the issue again.

**Closed as completed by lextm** 2016-05-30 08:42 UTC
Labels: bug
