### ISSUE TITLE
Error message on install (uninstall) on MonoDevelop 5.7

### ISSUE THREAD

**Issue by roman-yagodin** [xunit/xamarinstudio.xunit#5] opened 2015-04-13 05:57 UTC
Then trying to install (or uninstall) xUnit add-in on MonoDevelop 5.7 (from official Xamarin Debian repository), following error message displayed: "Could not read add-in description". After install, add-in listed in installed, but no new project nor file types are available.

**Comment by x2bool** [comment] 2015-04-13 15:02
I can't reproduce the "Could not read add-in description" issue. However, there are indeed no new project nor file types available. I will look at this.

**Comment by jacqueline-homan** [comment] 2015-05-31 23:06
This is what I get...
![screenshot from 2015-05-31 19 05 45](https://cloud.githubusercontent.com/assets/3537889/7904424/2045350e-07c8-11e5-855e-a15bb5d59f0e.png)

![screenshot from 2015-05-31 19 07 45](https://cloud.githubusercontent.com/assets/3537889/7904434/66330b22-07c8-11e5-9939-3d0a50daf007.png)

**Comment by x2bool** [comment] 2015-06-01 10:22
@jacqueline-homan Is NUnit addin installed and enabled? What version does it have?

**Comment by jacqueline-homan** [comment] 2015-06-01 20:02
@x2bool , I have NUnit installed. And the only package of NUnit that was available to me to install was v2.6.4. Having this level of difficulty with the ONLY IDE available to me for F# as someone on a Linux machine is extremely disappointing, as I am trying to work through the Pluralsight tutorials (which are all given in Visual Studio, which I don't have and can't use as I am on Linux) to learn F# and also eventually to learn C# too. And now I can't do it because Monodevelop is messing up and not working right for me. I looked on Stackoverflow for some help and found someone else was having the exact same problem as me. Additionally, I am having problems with being unable to open the NuGet packages list for adding NuGet packages without Monodevelop crashing and closing on me. I am new-ish to learning programming, so I am not at all confident that I'd be able to implement the solution I saw on Stackoverflow, which is to totally purge Monodevelop from my computer and reinstall it all over again. I had a LOT of difficulty with getting it installed the first time, and I don't want to totally lose my F# installation either. Or mess up other stuff in my computer. I don't have anyone I can really reach out to for help with it, either.

**Comment by emitelma** [comment] 2015-06-08 02:19
I am not getting "Run Item" in Project context menu. How do I run the tests? No new Project or File types. I am using Xamarin Studio running on a Mac.

**Comment by x2bool** [comment] 2015-06-08 07:20
Alright, I am downgrading to the previous version until I can figure out what's going on. Expect plugin update soon.

**Comment by emitelma** [comment] 2015-06-08 15:08
@x2bool Apologies for the confusion. I'd like to clarify something. I am running a Mac with XamarinStudio v5.8.3 (Build 1) and I had no errors during install of xUnit add-in from Gallery. But I don't get "Run Item" context menu nor no new Project or File Types. NUnit works ok. ( Mono 3.12.x )

**Comment by x2bool** [comment] 2015-06-14 12:23
The plugin is reverted to the previous version and published.

Instructions:
1) Install the plugin using Xamarin Studio's addin manager
2) Make sure NUnit and xUnit plugins are _enabled_
3) Install xUnit libraries manually or using NuGet (Install-Package xunit -Version 1.9.2)
4) Again, make sure it's 1.9.x, and not 2.x
5) Build your project
6) At this point you should see your tests on the "Unit tests" pad

**Comment by roman-yagodin** [comment] 2015-07-09 10:12
I was able to add xunit 1.9.2 to the solution and even build tests project, but soon after that Xamarin Studio (on Windows) start crushing on solution load during package update. 

Also, 1.9.2 missing many useful features (e.g. TheoryAttribute).

**Comment by x2bool** [comment] 2015-07-09 11:21
@roman-yagodin I think you have to install xunit.extensions package to have theories in 1.x.

> Install-Package xunit.extensions -Version 1.9.2

**Comment by roman-yagodin** [comment] 2015-07-10 06:59
Still no progress with XS 5.9.2 - I've added xunit and xunit.extensions 1.9.2 to the library type project, add references to them, tests project build OK, NUnit & xUnit addins are enabled - but still no tests seen in the Unit tests pad, and soon after XS start crushing on solution load during package update.

**Comment by x2bool** [comment] 2015-07-10 13:33
This is wierd! It works for me just fine, but so many people seem to have problems. I will test everything with a fresh Linux installation. Can't promise anything with Windows and Mac though.

**Comment by lextm** [comment] 2016-05-28 07:36
Can anyone try to install 0.5.2 on Xamarin Studio 5.10 following readme.md? I think this issue has been resolved.

**Comment by lextm** [comment] 2016-05-30 08:46
Temp close this one.

If anyone still suffers the installation issue, please re-open it.

**Closed as completed by lextm** 2016-05-30 08:46 UTC
Labels: question

**Comment by roman-yagodin** [comment] 2016-05-30 09:21
0.5.2 working fine, thanks!
