### ISSUE TITLE
Async test results aren't displayed in Xamarin Studio 6.0.1 on OSX

### ISSUE THREAD

**Issue by eviltak** [xunit/xamarinstudio.xunit#32] opened 2016-07-04 15:35 UTC
Running async tests through this plugin seems to have no effect. The Test Results page shows the test result section for the test, but with no status. The same tests execute and return the desired results when run from the [xUnit Console Runner](https://www.nuget.org/packages/xunit.runner.console). 

![screen shot 2016-07-04 at 20 58 50](https://cloud.githubusercontent.com/assets/8018181/16565345/491e38de-422a-11e6-9f5b-a65bc96b40d7.png)

The test being run above is a simple async test that should always fail.

```
[Fact]
public async Task CollectionsService_SearchTest()
{
    await Task.Delay(5000);
    Assert.True(false);
}
```

The above test fails successfully (excuse the oxymoron) when run from the [xUnit Console Runner](https://www.nuget.org/packages/xunit.runner.console).

I don't see any errors anywhere in the IDE, and synchronous tests run properly.

On debugging, it looks like _something_ happens whenever the test reaches an `await`. Up to that point, the test executes in the IDE without any problems.

**Comment by eviltak** [comment] 2016-07-04 16:01
After doing some debugging, looks like the extension _does_ get the correct results, but is not able to show them in the Test Results window. Whenever the Unit Tests window is refreshed (i.e. a small synchronous test is run), the icon beside the test shows the correct result.

**Comment by lextm** [comment] 2016-07-05 04:57
Thanks for reporting this. As we are moving to a new architecture soon (see #31), will check if that resolves this, as well as other known issues.

**Comment by eviltak** [comment] 2016-07-05 07:48
After doing a lot more debugging, looks like the [xUnit Runner Utility](https://www.nuget.org/packages/xunit.runner.utility/) package does not make the process wait till the test is finished. I'm looking for a solution, but it looks like the problem is in the runner package. There is a hacky workaround, but I don't think that it is a _good_ workaround.

**Comment by lextm** [comment] 2016-07-09 01:27
BTW, I tested this with Xamarin Studio 6.0.1 and 0.6.6 release of this add-in, and could not reproduce this issue. Maybe you should update to 0.6.6 first.

**Comment by lextm** [comment] 2016-07-10 12:29
Tested after merging #31 and still could not reproduce this issue. Close it now. Please reopen if more info can be shared.

**Closed as completed by lextm** 2016-07-10 12:29 UTC
Labels: bug
